// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RimacTask.DbContexts;

namespace RimacTask.Migrations
{
    [DbContext(typeof(NetworkNodeDbContext))]
    [Migration("20211106192129_InitalMigration")]
    partial class InitalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("RimacTask.Models.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("NetworkNodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NetworkNodeId");

                    b.ToTable("MessagesData");
                });

            modelBuilder.Entity("RimacTask.Models.NetworkNodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NetworkNodeData");
                });

            modelBuilder.Entity("RimacTask.Models.Signals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BitStart")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("SignalsData");
                });

            modelBuilder.Entity("RimacTask.Models.Messages", b =>
                {
                    b.HasOne("RimacTask.Models.NetworkNodes", "NetworkNode")
                        .WithMany("Messages")
                        .HasForeignKey("NetworkNodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NetworkNode");
                });

            modelBuilder.Entity("RimacTask.Models.Signals", b =>
                {
                    b.HasOne("RimacTask.Models.Messages", "Message")
                        .WithMany("Signals")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Message");
                });

            modelBuilder.Entity("RimacTask.Models.Messages", b =>
                {
                    b.Navigation("Signals");
                });

            modelBuilder.Entity("RimacTask.Models.NetworkNodes", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
